<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Parameter;

class ParameterSeeder extends Seeder
{
    use ResolvesAdminUser;

    public function run(): void
    {
        $data = [
            ['Ahli Waris Anggota Kelompok(n)', '1'],
            ['Alamat', '1'],
            ['Alamat Anggota Kelompok(n)', '1'],
            ['Anggota', '1'],
            ['Angsuran', '1'],
            ['Angsuran Ke', '1'],
            ['Angsuran Terbilang', '1'],
            ['AngsuranBagiHasil', '2'],
            ['AngsuranPokok', '2'],
            ['Bagi Hasil', '1'],
            ['Bagi Hasil Per Bulan', '1'],
            ['Bagi Hasil Per Bulan Terbilang', '1'],
            ['Bagi Hasil Terbilang', '1'],
            ['BagiHasilNominal', '2'],
            ['Bulan (Tanggal) Romawi', '1'],
            ['Bulan Terbilang(Jatuh Tempo)', '1'],
            ['Bulan Terbilang(Tanggal)', '1'],
            ['Bulan(Jatuh Tempo)', '1'],
            ['Bulan(Tanggal)', '1'],
            ['DendaTunggakan', '2'],
            ['Enter', '1'],
            ['Hari Terbilang(Jatuh Tempo)', '1'],
            ['Hari Terbilang(Tanggal)', '1'],
            ['Hari(Jatuh Tempo)', '1'],
            ['Hari(Tanggal)', '1'],
            ['Jaminan', '1'],
            ['Jaminan Detail Keterangan(n)', '1'],
            ['Jaminan Detail Nama(n)', '1'],
            ['Jaminan Detail Nilai(n)', '1'],
            ['Jangka Waktu', '1'],
            ['Jangka Waktu Terbilang', '1'],
            ['Jatuh Tempo', '1'],
            ['Jatuh Tempo Terbilang', '1'],
            ['Jenis Angsuran', '1'],
            ['Jenis Identitas', '1'],
            ['Jenis Kelamin', '1'],
            ['Jumlah Saham', '1'],
            ['Kelompok', '1'],
            ['Kode Kantor', '1'],
            ['Kota', '1'],
            ['KSP', '1'],
            ['Manajer', '1'],
            ['Marketing', '1'],
            ['Nama Anggota Kelompok(n)', '1'],
            ['No. Anggota', '1'],
            ['No. Anggota Kelompok(n)', '1'],
            ['No. HP', '1'],
            ['No. Identitas', '1'],
            ['No. KTP Anggota Kelompok(n)', '1'],
            ['No. Pinjaman', '1'],
            ['No. Simpanan', '1'],
            ['No. Simpanan Berjangka', '1'],
            ['Nominal', '2'],
            ['Nominal Blokir', '1'],
            ['Nominal Setor', '1'],
            ['Nominal Simpanan', '1'],
            ['Nominal Simpanan Berjangka', '1'],
            ['Nominal Simpanan Berjangka Terbilang', '1'],
            ['Nominal Simpanan Terbilang', '1'],
            ['NPWP', '1'],
            ['Pejabat', '1'],
            ['Pekerjaan', '1'],
            ['Pekerjaan Anggota Kelompok(n)', '1'],
            ['Plafon', '1'],
            ['Plafon Terbilang', '1'],
            ['Produk Pinjaman', '1'],
            ['Produk Simpanan', '1'],
            ['Produk Simpanan Berjangka', '1'],
            ['Saham', '1'],
            ['Saksi Alamat(n)', '1'],
            ['Saksi No. KTP(n)', '1'],
            ['Saksi Pekerjaan(n)', '1'],
            ['Saksi Tanggal Lahir(n)', '1'],
            ['Saksi Tempat Lahir(n)', '1'],
            ['Saksi(n)', '1'],
            ['Saldo Simpanan Debet', '1'],
            ['Satuan Waktu', '1'],
            ['Sektor', '1'],
            ['SisaBagiHasil', '2'],
            ['SisaPinjaman', '2'],
            ['SisaPokok', '2'],
            ['Tahun(Jatuh Tempo)', '1'],
            ['Tahun(Tanggal)', '1'],
            ['Tanggal', '1'],
            ['Tanggal Gabung', '1'],
            ['Tanggal Hari Ini', '1'],
            ['Tanggal Hari Ini Terbilang', '1'],
            ['Tanggal Hari Ini/', '1'],
            ['Tanggal Lahir', '1'],
            ['Tanggal/', '1'],
            ['Telepon', '1'],
            ['Tempat Lahir', '1'],
            ['Terlambat', '2'],
            ['Tgl Blokir', '1'],
            ['Tgl. Pencairan Pinjaman', '1'],
            ['Tgl. Setor', '1'],
            ['Total Pinjaman', '1'],
            ['Total Pinjaman Terbilang', '1'],
            ['Total Sisa Pinjaman', '1'],
            ['Total Sisa Pinjaman Terbilang', '1'],
            ['Tunggakan', '2'],
            ['Tunggakan Pinjaman', '1'],
            ['User', '1'],
            ['X Angsur', '1'],
            ['X Sisa', '1'],
        ];

        foreach ($data as [$nama, $jenis]) {
            Parameter::firstOrCreate(
                ['nama' => $nama],
                [
                    'jenis'   => $jenis,
                    'user_id' => $this->adminUserId(),
                ]
            );
        }
    }
}
